language: node_js
dist: trusty
sudo: required
node_js:
  - '8'
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
env:
  - DOCKER_COMPOSE_VERSION=1.16.1
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - env
  - docker-compose pull
  - yarn test
deploy:
  provider: npm
  email: tommy.brunn@gmail.com
  on:
    tags: true
    repo: Nevon/kafkajs-dlq